site_name: Reproschema documentation
repo_name: "ReproNim/reproschema"
repo_url: "https://github.com/ReproNim/reproschema"
copyright: "CC-BY 4.0"

# This will use Material them
theme:
  name: "material"
  language: "en"
  favicon: img/favicon.png
  logo: img/favicon_on_white.png
  palette:
    primary: "dark blue"
    accent: "light blue"

# Pages
nav:
  - Welcome: "index.md"
  - Introduction: "01_introduction.md"
  - Project structure: "20_project_structure.md"
  - Schema: "30_schema.md"
  - Using reproschema - a tutorial:
      - Intro: "40_using_reproschema.md"
      - Creating a new protocol: "41_create_new_protocol.md"
      - Creating a new activity: "42_create_new_activity.md"
      - Tips to make your life easier: "43_tips_to_make_your_life_easier.md"
      - Translate a questionnaire: "44_translating_an_activity.md"
      - Demographic information : "45_collecting_demographics_information.md"
  # - Testing your schema and collecting data: "testing_using_schema.md"
  # - Contribute to the project:
  #     - Reproschema: "81_contribute_to_schema.md"
  #     - Assesement library: "82_contribute_to_library.md"
  #     - Python package: "83_contribute_to_python.md"
  #     - User-interface: "84_contribute_to_ui.md"
  - FAQ: "98_FAQ.md"
  - Glossary: "99_glossary.md"
  - About this doc: "100_about_this_doc.md"

# list of extension
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.critic
